name: laravel-personal-website

services:
  app:
    image: ${DOCKER_REGISTRY:-localhost}/laravel-personal-website:${IMAGE_TAG:-latest}
    build:
      context: .
    working_dir: /app
    entrypoint: ["docker-init/entrypoint-production.sh"]
    ports:
      - '${DOCKER_APP_PORT:-1006}:8000'
    networks:
      - app-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - app-data:/app/storage
      - app-env:/app/.env
      - ./docker-init:/app/docker-init
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  app-data:
  app-env:
  redis-data:
