name: laravel-personal-website

services:
  app:
    container_name: laravel.test
    build:
      context: .
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    working_dir: /app
    ports:
      - '${APP_PORT:-80}:8000'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    depends_on:
      - mariadb
      - redis
      - selenium
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome
    restart: unless-stopped
    ports:
      - "${SELENIUM_PORT:-4444}:4444"
      - "${SELENIUM_VNC_PORT:-7900}:7900"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
