name: laravel-personal-website

services:
  app:
    container_name: laravel.test
    build:
      context: .
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["docker-init/entrypoint.sh"]
    ports:
      - '80:8000'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
      - /app/public/build
    depends_on:
      - mariadb
      - redis
      - selenium
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
