name: laravel-personal-website

services:
  app:
    container_name: laravel.test
    build:
      context: .
      args:
        INSTALL_XDEBUG: "true"
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["docker-init/entrypoint.sh"]
    ports:
      - '${APP_PORT:-80}:8000'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    depends_on:
      - mariadb
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

  # Services pour les tests Dusk E2E
  app-dusk:
    container_name: laravel.dusk
    build:
      context: .
      args:
        INSTALL_XDEBUG: "false"
    restart: unless-stopped
    working_dir: /app
    entrypoint: ["docker-init/entrypoint-dusk.sh"]
    env_file:
      - ./.env.dusk.docker
    ports:
      - '8001:8000'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
      - .env.dusk.docker:/app/.env
    depends_on:
      - selenium
    networks:
      - app-network
    profiles:
      - dusk

  selenium:
    image: selenium/standalone-chrome
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - app-network
    profiles:
      - dusk

networks:
  app-network:
    driver: bridge
