name: laravel-personal-website

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "${DOCKER_APP_PORT:-1006}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1

  app:
    build:
      context: .
      dockerfile: production.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-personal-website.rule=Host(`127.0.0.1`)"
      - "traefik.http.services.laravel-personal-website.loadbalancer.server.port=8000"
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - stack.env
    volumes:
      - app-data:/app/storage
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  app-data:
  redis-data:
